runtime: nodejs16  # Use the appropriate Node.js runtime version

env_variables:
  # Set your environment variables here
  PORT: 8080  # Use the desired port for your application

handlers:
  - url: /.*
    script: auto
